#!/usr/bin/env node

const inquirer = require("inquirer");
const Mocha = require("mocha");

inquirer.prompt({
  type: "confirm",
  name: "confirm",
  message: "Are you sure you want to test ./src/config.js for errors?"
}).then((answer) => {
  if (!answer.confirm) return;
  new Mocha().addFile("./test/configLint.js").run();
});
