#!/usr/bin/env node

const client = require("../src/client.js");

if (!client.cfg.priorityLabels) console.log("No priority labels were specified in config.js!");

async function getPriority(client, issues, label) {
  let response = await client.issues.getAll({
    filter: "all", state: "open", labels: label, per_page: 100
  });
  issues = issues.concat(response.data);
  while (client.hasNextPage(response)) {
    response = await client.getNextPage(response);
    issues = issues.concat(response.data);
  }
  return issues;
}

client.cfg.priorityLabels.forEach(async(label) => {
  const labels = await getPriority(client, [], label);
  if (!labels.length) return console.log(`There are no unclaimed issues with the "${label}" label!`);
  let report = `\nUnclaimed issues labeled with the "${label}" label:`;
  labels.forEach((issue, index, array) => {
    if (!issue.assignees.length) {
      report += `\n* ${issue.repository.full_name} — [${issue.title} (#${issue.number})](${issue.html_url})`;
    }
    if (index === array.length - 1) console.log(report);
  });
});
