#!/usr/bin/env node

const inquirer = require("inquirer");
const client = require("../src/client.js");

let username;

inquirer.prompt({
  type: "input",
  name: "username",
  message: "What's your GitHub username?"
}).then((answer) => {
  username = answer.username;
  return client.users.getForUser({
    username: username
  });
}).catch(() => {
  console.log("There isn't a GitHub account registered under that username! D: Try again.");
  process.exit(1);
}).then(() => {
  return client.repos.createForOrg({
    org: "zulipbot-testing", name: username, auto_init: true
  });
}).catch((ex) => {
  const errorMsg = JSON.parse(ex.message);
  if (ex.code === 422 &&
    errorMsg.errors[0].message === "name already exists on this account") {
    console.log("Nice try, you already have a test repository at",
      `https://github.com/zulipbot-testing/${username}. No extras :P`);
    process.exit(1);
  }
  throw ex;
}).then(() => {
  console.log(`Repository successfully created at https://github.com/zulipbot-testing/${username}!`);
  return client.repos.addCollaborator({
    owner: "zulipbot-testing", repo: username, username: username, permission: "admin"
  });
}).then(() => {
  console.log("You now have admin access to your test repository, use it wisely!");
  return client.orgs.addOrgMembership({
    org: "zulipbot-testing", username: username, role: "member"
  });
}).then(() => {
  console.log("Please accept your invitation to the zulipbot-testing organization ",
    "at https://github.com/zulipbot-testing.");
  console.log("Have fun testing!");
}).catch((ex) => {
  console.error(ex);
});
